image: node:latest

pages:
  cache:
    paths:
    - node_modules/

  stage: deploy
  script:
  - npm install -g @angular/cli@9.1.8
  - npm install
  - ng build --prod
  - mkdir public
  - mv dist/my-website/* public/
  artifacts:
    paths:
    - public
  only:
  - master